export const GISTS_SET = 'GISTS_SET'
export const FILE_SELECT = 'FILE_SELECT'
export const FILES_UPDATE = 'FILES_UPDATE'
export const EDITOR_CHANGE = 'EDITOR_CHANGE'
export const GITHUB_SET = 'GITHUB_SET'
